### ISSUE TITLE
Typeerror "record"

### ISSUE THREAD

**Issue by omy5123** [ebadi/OpenScenarioEditor#3] opened 2021-05-10 04:16 UTC
Hello, I have the same problem. I want to use it right away, how should I modify the code?

disable_ctrls = False , use_viewer = True , threads = True , record = False
Traceback (most recent call last):
File "OpenScenarioEditor.py", line 462, in openxml
self.gui.load_file(self.xmlfn)
File "/home/thang/OpenScenarioEditor/gui_qt.py", line 1119, in load_file
self.reload()
File "/home/thang/OpenScenarioEditor/gui_qt.py", line 885, in reload
self.pyesmini = PyEsmini(
TypeError: init() got an unexpected keyword argument 'record'

**Comment by eknabevcc** [comment] 2021-05-10 05:30
I haven't tested, but my best guess would be to change the lines [882-883](https://github.com/ebadi/OpenScenarioEditor/blob/c0ce8028ad6b5f8b9d4501e5da5cd9e4df740bd6/gui_qt.py#L882):
from
```
            ", record = ",
            record)
```
to:
```
            ", recordFile = ",
            "sim.dat" if record else "")
```

**Comment by ebadi** [comment] 2021-05-10 06:15
Thanks @omy5123 for reporting this issue.  The issue is now resolved. (Thanks @eknabevcc for the pointer) 

Please **remove** OpenScenario directory  and follow the [build instruction](https://github.com/ebadi/OpenScenarioEditor#build-and-run) and please let me know if you still have the same issue.

**Comment by omy5123** [comment] 2021-05-10 06:28
Thank you!! @ebadi @eknabevcc

**Comment by lsy234009** [comment] 2021-05-13 12:23
I add
           ' ", recordFile = ",
            "sim.dat" if record else "") '
but the problem still exists
~

**Comment by ebadi** [comment] 2021-05-13 16:50
Hi @lsy234009,
Please remove OpenScenario directory and follow the build instruction and let me know if you still have the same issue.

I close this issue and we can discuss your problem here
https://github.com/ebadi/OpenScenarioEditor/issues/4

**Closed by ebadi** 2021-05-13 16:50 UTC
Labels: bug
